[package]
name = "pamb_os"
version = "0.1.0"
authors = ["Deepak Sirone", "Arpan Kapoor"]

[lib]
crate-type = ["staticlib"]
 
[dependencies]
rlibc = "1.0.0"
spin = "0.3.4"

[profile.dev]
panic = "abort"
